### ISSUE TITLE
npm errors when using any node related pre-commits

### ISSUE THREAD

**Issue by EricDavidWells** [tier4/pre-commit-hooks-ros#104]
Noticed errors when using any of the hooks which specify `language: node`. 

Running on Ubuntu 20.04
pre-commit version `3.5.0
pre-commit-config.yaml:

```
  - repo: https://github.com/tier4/pre-commit-hooks-ros
    rev: v0.10.0
    hooks:
      # - id: flake8-ros
      - id: prettier-xacro
      - id: prettier-launch-xml
      - id: prettier-package-xml
      # - id: ros-include-guard
      - id: sort-package-xml
```

errors:
```
[INFO] Initializing environment for https://github.com/tier4/pre-commit-hooks-ros:prettier@2.8.7,@prettier/plugin-xml@2.2.0.
[INFO] Installing environment for https://github.com/tier4/pre-commit-hooks-ros.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/home/rico/.cache/pre-commit/repot_n4ea6k/node_env-default/bin/node', '/home/rico/.cache/pre-commit/repot_n4ea6k/node_env-default/bin/npm', 'pack')
return code: 254
stdout: (none)
stderr:
    (node:955063) ExperimentalWarning: Support for loading ES Module in require() is an experimental feature and might change at any time
    (Use `node --trace-warnings ...` to show where the warning was created)
    npm warn tarball tarball data for file:/home/rico/.cache/pre-commit/repot_n4ea6k/ (null) seems to be corrupted. Trying again.
    npm warn tarball tarball data for file:/home/rico/.cache/pre-commit/repot_n4ea6k/ (null) seems to be corrupted. Trying again.
    npm error code ENOENT
    npm error syscall lstat
    npm error path /home/rico/.cache/pre-commit/repot_n4ea6k/ode_env-default/bin/activate
    npm error errno -2
    npm error enoent ENOENT: no such file or directory, lstat '/home/rico/.cache/pre-commit/repot_n4ea6k/ode_env-default/bin/activate'
    npm error enoent This is related to npm not being able to find a file.
    npm error enoent
    npm error A complete log of this run can be found in: /home/rico/.npm/_logs/2024-10-17T18_35_28_469Z-debug-0.log
Check the log at /home/rico/.cache/pre-commit/pre-commit.log

```
